export const MENU_ACCESS = {
    SISTEMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CATALOGOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USUARIOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    ASIGNAR_PROYECTOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    MATRIZ_DOCUMENTAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    FORMATOS_IMPRESION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PISTAS_AUDITORIA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PAPELERA_RECICLAJE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROVEEDORES: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    PROYECTOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONTRATOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONSUMO_SERVICIOS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REINTEGROS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REPORTES: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REPORTES_CONTROL_DOCUMENTAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONSTRUIR_REPORTES: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REPORTE_FINANCIERO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    RESUMEN_FINANCIERO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    SEGUIMIENTO_DICTAMEN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    FACT_PEN_DEDUC_REINT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    ESTIMADO_PAGADO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    SEGUIMIENTO_CONCEPTO_SERV: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    ESTADO_FINANCIERO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    TABLERO_CONTROL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
}

export const PROCESOS = {
    CAT_GRAL_ADMIN: ["SAT_SISECOFI_ADMIN_SIS"],
    CAT_COMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CAT_COMP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    AP_PROY_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    AP_PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    AP_USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    AP_USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    MTZ_DOC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    FTO_IMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PIST_AUD_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PAP_RECIC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_VERI_GEN"],
    PROV_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_BTN_GUARDARDG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROV_TA_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROY_VTP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"],
    PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    PROY_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_BTN_GUARDARDG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_PLANEACION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_PROC_CIE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_STA_CERRADO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_FT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_AFM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    PROY_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_INFO_COM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_INFO_COM_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_PT_CARGA_PLAN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_PT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_PT_BTN_CALC_PORCENT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_PT_BTN_CALC_TP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_PP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_VRCP_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_VRCP_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"],
    PROY_VRCP_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"],
    PROY_VRCP_STA_REV_AP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_VRCP_STA_VAL_LP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_VRCP_STA_GEN_RCP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_VRCP_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_VRCP_STA_EPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_VTC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"],
    CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_IDENT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_DG_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_VYM_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_GSC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_BTN_VALIDAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CN_BTN_PP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_CLYDI_BTN_CARGAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_AIP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDPUV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDDLS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_PC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_NS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_AP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_STA_CIERRE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_PCM_BTN_PPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_CM_ASIG_PLANT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_CM_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_CM_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_CM_GD_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_ADMIN_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_ADMIN_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_EST_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_ESTIM_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CON_SERV_ESTIM_STA_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_ESTIM_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_DICT_STA_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_DICT_STA_SOLPAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_PAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_DICT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_PCONT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_DICT_PCONT_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_PCONV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_DICT_PCONV_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DEDUC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],
    CON_SERV_DICT_DEDUC_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_BTN_RECHAZA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_BTN_GEN_PROF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_SOLFAC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_FAC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_NC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_REINT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_REINT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONTDOC_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONTDOC_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_CONTDOC_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONSREP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_RES_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_SEG_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_FPDR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_EST_PAG_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_SPLS_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_EST_FIN_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_TAB_CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    ...MENU_ACCESS
}

export const PROCESOS_BK2 = {
    CAT_GRAL_ADMIN: ["SAT_SISECOFI_ADMIN_SIS"],
    CAT_COMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CAT_COMP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    AP_PROY_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    MTZ_DOC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    FTO_IMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PIST_AUD_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PAP_RECIC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_VERI_GEN"],
    PROV_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_DC_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROV_TA_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROY_VTP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"],
    PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    PROY_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_STA_PLANEACION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_PROC_CIE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_STA_CERRADO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_FT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_AFM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    PROY_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_INFO_COM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // => OK
    PROY_INFO_COM_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"], // => OK
    PROY_PT_CARGA_PLAN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_PT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // => OK
    PROY_PT_BTN_CALC_PORCENT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],// => OK
    PROY_PT_BTN_CALC_TP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_PP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"], // OK
    PROY_VRCP_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"], // OK
    PROY_VRCP_STA_REV_AP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_STA_VAL_LP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_STA_GEN_RCP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_STA_EPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    CONT_VTC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"],
    CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    CONT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    CONT_IDENT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_DG_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_VYM_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_GSC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_BTN_VALIDAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CN_BTN_PP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // => OK
    CONT_CLYDI_BTN_CARGAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_AIP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_IDPUV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_IDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_IDDLS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_PC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_NS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"], // => OK
    CONT_AP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_STA_CIERRE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_PCM_BTN_PPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_CM_ASIG_PLANT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_CM_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_CM_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_CM_GD_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", /* Roles agregados a peticion de Aylin y Carmen */ "SAT_SISECOFI_VERI_ESP_CON", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_PART_ADMIN_VERIF"], // OK
    CON_SERV_ADMIN_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_ADMIN_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_EST_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_ESTIM_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], //=> OK
    CON_SERV_ESTIM_STA_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"], // => OK
    CON_SERV_ESTIM_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"], // => OK
    CON_SERV_DICT_STA_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_STA_SOLPAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_PAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_PCONT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_PCONT_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_PCONV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"],// OK
    CON_SERV_DICT_PCONV_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_DEDUC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_DEDUC_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_DDP_BTN_RECHAZA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_DDP_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],// => OK
    CON_SERV_DICT_DDP_BTN_GEN_PROF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_SOLFAC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_FAC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],// => OK
    CON_SERV_DICT_NC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_REINT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    CON_SERV_DICT_REINT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK 
    REP_CONTDOC_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONTDOC_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_CONTDOC_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONSREP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_RES_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_SEG_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    REP_RESFIN_FPDR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_EST_PAG_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_SPLS_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_EST_FIN_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_TAB_CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    ...MENU_ACCESS
}

export const PROCESOS_BK = {
    CAT_GRAL_ADMIN: ["SAT_SISECOFI_ADMIN_SIS"],
    CAT_COMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CAT_COMP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    AP_PROY_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_USR_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    AP_USR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // OK
    MTZ_DOC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    FTO_IMP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PIST_AUD_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PAP_RECIC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_VERI_GEN"],
    PROV_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROV_DC_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_LID_PRO"],
    PROV_DC_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROV_TA_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_TA_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROV_DT_DLT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_GES_TIT_AUT"],
    PROY_VTP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"], // No se entiende como aplicar
    PROY_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // => OK
    PROY_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_STA_PLANEACION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], //=> BACK
    PROY_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], //=> BACK
    PROY_STA_PROC_CIE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], //=> BACK
    PROY_STA_CERRADO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], //=> BACK
    PROY_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], // => OK
    PROY_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"], //=> BACK
    PROY_FT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_AFM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    PROY_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_INFO_COM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    PROY_INFO_COM_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    PROY_PT_CARGA_PLAN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_PT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_PT_BTN_CALC_PORCENT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"],
    PROY_PT_BTN_CALC_TP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    PROY_PP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"], // OK
    PROY_VRCP_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON"], // OK
    PROY_VRCP_STA_REV_AP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_STA_VAL_LP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_STA_GEN_RCP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_LID_PRO"], // OK
    PROY_VRCP_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    PROY_VRCP_STA_EPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"], // OK
    CONT_VTC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_TDS_PROY"],
    CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_ALTA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_IDENT_STA_EJECUCION: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_DG_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_VYM_MODIF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_GSC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_RDS_BTN_VALIDAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CN_BTN_PP: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_CLYDI_BTN_CARGAR: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_AIP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_IDPUV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_IDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_IDDLS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_PC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_NS_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_APO_LID_PROY"],
    CONT_AP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_STA_CIERRE: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CONT_CM_PCM_BTN_PPROC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP"],
    CONT_CM_ASIG_PLANT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC"],
    CONT_CM_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_GES_DOC_CON"],
    CONT_CM_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CONT_CM_GD_DOWN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_ESP_CON", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_ADMIN_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_ADMIN_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"], // Casi OK, falta generales, registro de servicios dictaminados, deducciones/descuentos/penalizaciones, solicitud de factura, facturas, notas de crédito, solicitud de pago, gestión documental
    CON_SERV_EST_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT"],
    CON_SERV_ESTIM_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC"],
    CON_SERV_ESTIM_STA_ESTIM: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_ESTIM_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM"],
    CON_SERV_DICT_STA_DICT: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_STA_SOLPAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_PAG: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_INICIAL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_STA_CANCEL: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_PCONT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_PCONT_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_PCONV_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_PCONV_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_DEDUC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_VERI_GEN"], // OK
    CON_SERV_DICT_DEDUC_MONTO: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    CON_SERV_DICT_GD_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_GD_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_BTN_RECHAZA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_DDP_BTN_GEN_PROF: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_SOLFAC: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_FAC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_STA_PROFORMA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_NC_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_REINT_ADMIN: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CON_SERV_DICT_REINT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONTDOC_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONTDOC_DOWN_MASIVA: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    CONT_CONTDOC_DOWN_IND: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_MAT_DOC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_APO_LID_PROY", "SAT_SISECOFI_GES_DOC_CON", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_CONSREP_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_RES_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_SEG_DICT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
    REP_RESFIN_FPDR_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_EST_PAG_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_SPLS_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_ESTIM", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_RESFIN_EST_FIN_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"], // OK
    REP_TAB_CONT_CONS: ["SAT_SISECOFI_ADMIN_SIS", "SAT_SISECOFI_ADMIN_SIS_SEC", "SAT_SISECOFI_ADMIN_APO_ACP", "SAT_SISECOFI_GES_TIT_AUT", "SAT_SISECOFI_USU_CONS", "SAT_SISECOFI_LID_PRO", "SAT_SISECOFI_ADMIN_CON", "SAT_SISECOFI_PART_ADMIN_DICT", "SAT_SISECOFI_PART_ADMIN_VERIF", "SAT_SISECOFI_VERI_GEN", "SAT_SISECOFI_VERI_ESP_CON"],
}
