export const ROLES_bk = {
    PARTICIPANTES_EN_LA_ADMINISTRACION_DE_DICTAMEN: {
        rol: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_DICTAMEN',
        name: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_DICTAMEN'
    },
    PARTICIPANTES_EN_LA_ADMINISTRACION_DE_LA_VERIFICACION: {
        rol: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_LA_VERIFICACION',
        name: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_LA_VERIFICACION'
    },
    VERIFICADOR_GENERAL: {
        rol: 'VERIFICADOR_GENERAL',
        name: 'VERIFICADOR_GENERAL'
    },
    VERIFICADOR_ESPECIFICO_DEL_CONTRATO: {
        rol: 'VERIFICADOR_ESPECIFICO_DEL_CONTRATO',
        name: 'VERIFICADOR_ESPECIFICO_DEL_CONTRATO'
    },
    TODOS_LOS_PROYECTOS: {
        rol: 'TODOS_LOS_PROYECTOS',
        name: 'TODOS_LOS_PROYECTOS'
    },
    ADMINISTRADOR_DEL_SISTEMA_SECUNDARIO: {
        rol: 'ADMINISTRADOR_DEL_SISTEMA_SECUNDARIO',
        name: 'ADMINISTRADOR_DEL_SISTEMA_SECUNDARIO'
    },
    ADMINISTRADOR_MATRIZ_DOCUMENTAL: {
        rol: 'ADMINISTRADOR_MATRIZ_DOCUMENTAL',
        name: 'ADMINISTRADOR_MATRIZ_DOCUMENTAL'
    },
    APOYO_ACPPI: {
        rol: 'APOYO_ACPPI',
        name: 'APOYO_ACPPI'
    },
    APOYO_AL_LIDER_DE_PROYECTO: {
        rol: 'APOYO_AL_LIDER_DE_PROYECTO',
        name: 'APOYO_AL_LIDER_DE_PROYECTO'
    },
    GESTOR_TITULOS_DE_AUTORIZACION: {
        rol: 'GESTOR_TITULOS_DE_AUTORIZACION',
        name: 'GESTOR_TITULOS_DE_AUTORIZACION'
    },
    GESTOR_DOCUMENTAL_CONTRATO: {
        rol: 'GESTOR_DOCUMENTAL_CONTRATO',
        name: 'GESTOR_DOCUMENTAL_CONTRATO'
    },
    USUARIO_CONSULTA: {
        rol: 'USUARIO_CONSULTA',
        name: 'USUARIO_CONSULTA'
    },
    LIDER_DE_PROYECTO: {
        rol: 'LIDER_DE_PROYECTO',
        name: 'LIDER_DE_PROYECTO'
    },
    ADMINISTRADOR_DEL_CONTRATO: {
        rol: 'ADMINISTRADOR_DEL_CONTRATO',
        name: 'ADMINISTRADOR_DEL_CONTRATO'
    },
    PARTICIPANTES_EN_LA_ADMINISTRACION_DE_ESTIMACIONES: {
        rol: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_ESTIMACIONES',
        name: 'PARTICIPANTES_EN_LA_ADMINISTRACION_DE_ESTIMACIONES'
    },
    ADMINISTRADOR_DEL_SISTEMA: {
        rol: 'ADMINISTRADOR_DEL_SISTEMA',
        name: 'ADMINISTRADOR_DEL_SISTEMA'
    }
}

export const ROLES = {
    ADMINISTRADOR_DEL_SISTEMA: {
        name: "ADMINISTRADOR DEL SISTEMA",
        rol: "SAT_SISECOFI_ADMIN_SIS"
    },
    ADMINISTRADOR_DEL_SISTEMA_SECUNDARIO: {
        name: "ADMINISTRADOR DEL SISTEMA SECUNDARIO",
        rol: "SAT_SISECOFI_ADMIN_SIS_SEC"
    },
    ADMINISTRADOR_MATRIZ_DOCUMENTAL: {
        name: "ADMINISTRADOR MATRIZ DOCUMENTAL",
        rol: "SAT_SISECOFI_ADMIN_MAT_DOC"
    },
    APOYO_ACPPI: {
        name: "APOYO ACPPI",
        rol: "SAT_SISECOFI_ADMIN_APO_ACP"
    },
    APOYO_AL_LÍDER_DE_PROYECTO: {
        name: "APOYO AL LÍDER DE PROYECTO",
        rol: "SAT_SISECOFI_APO_LID_PROY"
    },
    GESTOR_TÍTULOS_DE_AUTORIZACIÓN: {
        name: "GESTOR TÍTULOS DE AUTORIZACIÓN",
        rol: "SAT_SISECOFI_GES_TIT_AUT"
    },
    GESTOR_DOCUMENTAL_CONTRATO: {
        name: "GESTOR DOCUMENTAL CONTRATO",
        rol: "SAT_SISECOFI_GES_DOC_CON"
    },
    USUARIO_CONSULTA: {
        name: "USUARIO CONSULTA",
        rol: "SAT_SISECOFI_USU_CONS"
    },
    LÍDER_DE_PROYECTO: {
        name: "LÍDER DE PROYECTO",
        rol: "SAT_SISECOFI_LID_PRO"
    },
    ADMINISTRADOR_DEL_CONTRATO: {
        name: "ADMINISTRADOR DEL CONTRATO",
        rol: "SAT_SISECOFI_ADMIN_CON"
    },
    PARTICIPANTES_EN_LA_ADMINISTRACIÓN_DE_ESTIMACIONES: {
        name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE ESTIMACIONES",
        rol: "SAT_SISECOFI_PART_ADMIN_ESTIM"
    },
    PARTICIPANTES_EN_LA_ADMINISTRACIÓN_DE_DICTAMEN: {
        name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE DICTAMEN",
        rol: "SAT_SISECOFI_PART_ADMIN_DICT"
    },
    PARTICIPANTES_EN_LA_ADMINISTRACIÓN_DE_LA_VERIFICACIÓN: {
        name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE LA VERIFICACIÓN",
        rol: "SAT_SISECOFI_PART_ADMIN_VERIF"
    },
    VERIFICADOR_GENERAL: {
        name: "VERIFICADOR GENERAL",
        rol: "SAT_SISECOFI_VERI_GEN"
    },
    VERIFICADOR_ESPECIFICO_DEL_CONTRATO: {
        name: "VERIFICADOR ESPECIFICO DEL CONTRATO",
        rol: "SAT_SISECOFI_VERI_ESP_CON"
    },
    TODOS_LOS_PROYECTOS: {
        name: "TODOS LOS PROYECTOS",
        rol: "SAT_SISECOFI_TDS_PROY"
    }
}

export const ROLES_ARRAY = [
    { name: "ADMINISTRADOR DEL SISTEMA", rol: "SAT_SISECOFI_ADMIN_SIS" },
    { name: "ADMINISTRADOR DEL SISTEMA SECUNDARIO", rol: "SAT_SISECOFI_ADMIN_SIS_SEC" },
    { name: "ADMINISTRADOR MATRIZ DOCUMENTAL", rol: "SAT_SISECOFI_ADMIN_MAT_DOC" },
    { name: "APOYO ACPPI", rol: "SAT_SISECOFI_ADMIN_APO_ACP" },
    { name: "APOYO AL LÍDER DE PROYECTO", rol: "SAT_SISECOFI_APO_LID_PROY" },
    { name: "GESTOR TÍTULOS DE AUTORIZACIÓN", rol: "SAT_SISECOFI_GES_TIT_AUT" },
    { name: "GESTOR DOCUMENTAL CONTRATO", rol: "SAT_SISECOFI_GES_DOC_CON" },
    { name: "USUARIO CONSULTA", rol: "SAT_SISECOFI_USU_CONS" },
    { name: "LÍDER DE PROYECTO", rol: "SAT_SISECOFI_LID_PRO" },
    { name: "ADMINISTRADOR DEL CONTRATO", rol: "SAT_SISECOFI_ADMIN_CON" },
    { name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE ESTIMACIONES", rol: "SAT_SISECOFI_PART_ADMIN_ESTIM" },
    { name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE DICTAMEN", rol: "SAT_SISECOFI_PART_ADMIN_DICT" },
    { name: "PARTICIPANTES EN LA ADMINISTRACIÓN DE LA VERIFICACIÓN", rol: "SAT_SISECOFI_PART_ADMIN_VERIF" },
    { name: "VERIFICADOR GENERAL", rol: "SAT_SISECOFI_VERI_GEN" },
    { name: "VERIFICADOR ESPECIFICO DEL CONTRATO", rol: "SAT_SISECOFI_VERI_ESP_CON" },
    { name: "TODOS LOS PROYECTOS", rol: "SAT_SISECOFI_TDS_PROY" }
]

