export const MESSAGGES = {
    MSG001: "Información guardada correctamente.",
    MSG002: "El proyecto no tiene asignado ninguna plantilla documental.",
    MSG003: "Se perderán todos los cambios realizados. ¿Está seguro de que desea continuar?",
    MSG004: "Se modificará el “Estatus del RCP” a “Cancelado”. ¿Está seguro de que desea continuar?",
    MSG005: "Favor de ingresar los datos obligatorios",
    MSG006: "Ocurrió un error al guardar el registro, favor de intentar nuevamente (PA01).",
    MSG007: "Ocurrió un error al consultar la información, favor de intentar nuevamente (PA01).",
    MSG008: "Ocurrió un error al exportar la información, favor de intentar nuevamente (PA01).",
    MSG009: "¿Está seguro de que desea regresar? Se perderán todos los cambios no guardados.",
    MSG010: "La estructura de la información ingresada es incorrecta. Intente nuevamente.",
    MSG011: "Se modificará el “Estatus RCP” a “En proceso”. ¿Está seguro de que desea continuar?",
    MSG012: "Se modificará el “Estatus RCP” a “Revisado por Área de Planeación”. ¿Está seguro de que desea continuar?",
    MSG013: "Se modificará el “Estatus RCP” a “Validado por Líder de Proyecto”. ¿Está seguro de que desea continuar?",
    MSG014: "Aún existen entregables con estatus “Pendiente”. Intente nuevamente.",
    MSG015: "Las fechas no pueden ser menor a la fecha de inicio del proyecto o mayor a la fecha fin del proyecto.",
    MSG016: "Error al generar el enlace y contraseña. Intente nuevamente.",
    MSG017: "No puedes continuar si el “Estatus del proyecto” está en “Proceso de cierre”.",
}